services:
  - type: web
    name: tradebot-api
    runtime: go
    region: singapore
    plan: free
    buildCommand: go mod download && go build -o main
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: SUPABASE_HOST
        sync: false
      - key: SUPABASE_PASSWORD
        sync: false
